title: Azathought
description: >  
  Awesome, geeky things.  
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.azathought.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Azathought # add your name
author-img: caricature.png # add your photo
about-author: A geek in Washington, DC. # add description
twitter: azathought # add your Twitter handle
instagram: azathought
tumblr: azathought

# paging
paginate: 10
paginate_path: "/blog/page:num/"


# Disqus
discus-identifier: azathought

# Tracker
analytics: UA-13117692-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

gems: [jekyll-paginate]

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "tumblr_files"]
