title: Azathought
description: >  
  Awesome, geeky things.  
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.azathought.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Azathought # add your name
author-img: caricature.png # add your photo
about-author: A geek in Washington, DC. # add description
###twitter: azathought # add your Twitter handle
instagram: azathought
instagram2: azathought_games

# paging
paginate: 8
paginate_path: "/blog/page:num/"


# Disqus
discus-identifier: azathought

# Tracker
analytics: UA-13117692-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

gems: 
  - jekyll-paginate
  - jekyll-feed

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "tumblr_files"]
